//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunchRecord_Table
    {
        public string punch_addr { get; set; }
        public string punch_notes { get; set; }
        public int punch_employee_id { get; set; }
        public int punch_type_id { get; set; }
        public int punch_id { get; set; }
        public System.DateTime punch_datetime { get; set; }
        public string punch_img { get; set; }
    
        public virtual Account_DataTable Account_DataTable { get; set; }
        public virtual punchType_Table punchType_Table { get; set; }
    }
}
