//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PunchRecord
    {
        public string vw_employee { get; set; }
        public string vw_type { get; set; }
        public string vw_addr { get; set; }
        public string vw_notes { get; set; }
        public string vw_img { get; set; }
        public System.DateTime vw_datetime { get; set; }
        public int id { get; set; }
    }
}
